config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :categories, except: %i[destroy] do
    resources :pictures, only: %i[index]
  end

  resources :pictures, only: %i[index show] do
    resources :negative_likes, only: %i[create]
    resources :positive_likes, only: %i[create]
    resources :comments, only: %i[create]
  end

  resource :users, only: %i[show edit update]

  root to: 'categories#index'
end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :positive_likes
  has_many :negative_likes
  has_many :categories

  # has_many :pictures, :through => :likes, :uniq => true
  has_many :pictures
  has_many :comments, dependent: :destroy

  validates :email, presence: true, uniqueness: true
  validates :first_name, :last_name, presence: true

  def full_name
    [first_name, last_name].join(' ')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if current_user.update(user_params)
        format.html { redirect_to user_path(current_user), notice: 'Is Updated!' }
        format.json
      else
        format.html { render action: 'edit' }
        format.json { render json: current_user.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  private

    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end
end

app/views/users/edit.html.haml
.col-lg-6
  %h4
    = current_user.full_name
  - if current_user.errors.any?
    %h3 Erros:
    %ul
      - current_user.errors.full_messages.each do |message|
        %li
          = message
  =form_for current_user, html: { multipart: true, class: 'form-horizontal' } do |f|
    .form-group
      .col-sm-2.control-label
        = f.label :first_name
      .col-sm-8
        = f.text_field :first_name, class: 'form-control'
    .form-group
      .col-sm-2.control-label
        = f.label :last_name
      .col-sm-8
        = f.text_field :last_name, class: 'form-control'
    %hr
    .form-group
      .col-sm-12
        = f.button 'Update', class: 'btn btn-success'
        = link_to 'Back', user_path, class: 'btn btn-default'

app/views/users/show.html.haml
.col-lg-6
  %h5
    = current_user.full_name
  %hr
  %dl.dl-horizontal
    %dt First name:
    %dd= current_user.first_name
    %dt Last_name:
    %dd= current_user.last_name
  .pull-right{ style: 'padding-top: 10px;' }
    = link_to 'Edit', edit_users_path, class: 'btn btn-primary'
    = link_to 'On home page', root_path, class: 'btn btn-default'
  %hr