config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :categories, except: %i[destroy] do
    resources :pictures, only: %i[index]
  end

  resources :pictures, only: %i[index show] do
    resources :negative_likes, only: %i[create]
    resources :positive_likes, only: %i[create]
    resources :comments, only: %i[create]
  end

  resource :users, only: %i[show edit update]

  root to: 'categories#index'
end

app/views/shared/_dialog.html.haml
#dialog.modal.fade{ tabindex: -1, role: 'dialog', aria: { label: 'generalModalLabel', hidden: true } }
  .modal-dialog.modal-lg.event-dialog
    .modal-content
      .modal-header
        %button.close{ aria: { label: 'Close' }, data: { dismiss: 'modal' }, type: 'button' }
          %span{ aria: { hidden: 'true' } } ×
        %h3.modal-title

      .modal-body

app/views/shared/_header.html.haml
%nav.navbar-inverse.navbar-fixed-top
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{ aria: { expanded: 'false' }, data: { target: '#bs-navbar-collapse-1', toggle: 'collapse' }, type: 'button' }
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Pictures', root_path, class: 'navbar-brand'
    #bs-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li
          = link_to '#', class: 'dropdown-toggle', aria: { expanded: 'false', haspopup: 'false' },
                             data: { toggle: 'dropdown' }, role: 'button' do
            Categories
            %span.caret
          %ul.dropdown-menu
            %li
              = link_to categories_path do
                %i.glyphicon.glyphicon-th-list
                Categories List
            %li
              = link_to new_category_path, class: '.dropdown-toggle.btn-dialog',
                data: { toggle: :modal, target: '#dialog', remote: true } do
                %i.glyphicon.glyphicon-folder-close
                New Category
        %li
          = link_to 'All Pictures', pictures_path
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li= link_to current_user.full_name, users_path
          %li= link_to 'Log out', destroy_user_session_path(current_user), method: :delete
        - else
          %li
            = link_to 'Sign up', new_user_registration_path
            = "or #{link_to 'Sign in', new_user_session_path}"