config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :categories, except: %i[destroy] do
    resources :pictures, only: %i[index]
  end

  resources :pictures, only: %i[index show] do
    resources :negative_likes, only: %i[create]
    resources :positive_likes, only: %i[create]
    resources :comments, only: %i[create]
  end

  resource :users, only: %i[show edit update]

  root to: 'categories#index'
end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :pictures, dependent: :destroy
  belongs_to :user

  validates :name, presence: true, uniqueness: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :set_category, only: %i[show edit update]

  def index
    @category = current_user.categories.build
    @categories = Category.all.preload(:pictures)
  end

  def new
    @category = current_user.categories.build
  end

  def show
  end

  def edit
  end

  def create
    @category = current_user.categories.build(category_params)
    respond_to do |format|
      if @category.save
        format.html { redirect_to category_path(@category), notice: 'Is Created!' }
        format.json
      else
        format.js
      end
    end
  end

  def update

    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_path(@category), notice: 'Is Updated!' }
        format.json
      else
        format.html { render action: 'edit' }
        format.json { render json: @category.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper

  def return_error_list
    @category.errors.full_messages.collect{ |msg| "<li>#{msg}</li>" }.join('').html_safe
  end
end

app/helpers/searches/categories_helper.rb
module Searches::CategoriesHelper
end

app/views/categories/_form.html.haml
= form_for @category do |f|
  -if @category.errors.any?
    #error_explanation
      %h2= "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
      %ul
        - @category.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/categories/_new.html.haml
= form_for category, data: { remote: true } do |f|
  #error_explanation
    %ul

  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control', id: 'category_name',
      data: { autocomplete_source: searches_categories_path, remote: true }
  .actions
    = f.submit 'Save', class: 'btn btn-default'

app/views/categories/create.js.erb
$("#error_explanation ul").html("<%= escape_javascript(return_error_list) %>")

app/views/categories/edit.html.haml
%h1 Editing category

= render 'form'

= link_to 'Show', @category
\|
= link_to 'Back', categories_path

app/views/categories/index.html.haml
.row
  .col-lg-8.col-lg-offset-2{ style: 'padding-bottom: 30px;' }
    -#.panel-body
    -#  .input-group
    -#    = text_field_tag :name, nil, id: 'tags',
    -#                                           placeholder: 'Search for...', class: 'form-control',
    -#                                           data: { autocomplete_source: searches_categories_path }
    -#    %span.input-group-btn
    -#      %button.btn.search
    -#        %i.glyphicon.glyphicon-search
.row
  %h1 The Top Liked Categories
  .row
    - @categories.each do |category|
      - if category.pictures.present?
        .col-xs-6.col-md-3
          = link_to category_pictures_path(category.id), class: 'category thumbnail' do
            = image_tag category.pictures.first.image.url(:medium)
          .caption
            %h3= category.name

app/views/categories/new.js.erb
$("#dialog h3.modal-title").text("New Category")
$("#dialog .modal-body").html("<%= escape_javascript(render partial: 'categories/new', locals: { category: @category }) %>")

app/views/categories/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @category.name

= link_to 'Edit', edit_category_path(@category)
\|
= link_to 'Back', categories_path